<?php $desktop_home_content=array (
  'rows' => 
  array (
    0 => 
     array(
       'id' => 'slider',
       'child' => 
      array (
        0 => 
         array(
           'id' => 'slider_right_box',
           'type' => 'box',
           'child' => 
          array (
            0 => 
             array(
               'type' => 'widget',
               'tag' => 'slider',
               'id' => 'slider_right_box-slider1',
            ),
          ),
        ),
      ),
    ),
    1 => 
     array(
       'id' => 'incredibleOffers',
       'child' => 
      array (
        0 => 
         array(
           'id' => 'bannerTop_right',
           'type' => 'box',
           'child' => 
          array (
            0 => 
             array(
               'id' => 'bannerTop_right_top',
               'type' => 'box',
               'child' => 
              array (
                0 => 
                 array(
                   'type' => 'html',
                   'tag' => 'img',
                   'id' => 'bannerTop_right_top-img4',
                ),
                1 => 
                 array(
                   'type' => 'html',
                   'tag' => 'img',
                   'id' => 'bannerTop_right_top-img5',
                ),
              ),
            ),
            1 => 
             array(
               'id' => 'bannerTop_right_bottom',
               'type' => 'box',
               'child' => 
              array (
                0 => 
                 array(
                   'type' => 'html',
                   'tag' => 'img',
                   'id' => 'bannerTop_right_bottom-img7',
                ),
                1 => 
                 array(
                   'type' => 'html',
                   'tag' => 'img',
                   'id' => 'bannerTop_right_bottom-img10',
                ),
              ),
            ),
          ),
        ),
        1 => 
         array(
           'id' => 'bannerTop_left',
           'type' => 'box',
           'child' => 
          array (
            0 => 
             array(
               'type' => 'html',
               'tag' => 'img',
               'id' => 'bannerTop_left-img6',
            ),
          ),
        ),
      ),
    ),
    2 => 
     array(
       'id' => 'middle_banner',
       'child' => 
      array (
        0 => 
         array(
           'id' => 'middle_banner_imagebox',
           'type' => 'box',
           'child' => 
          array (
            0 => 
             array(
               'type' => 'html',
               'tag' => 'img',
               'id' => 'middle_banner_imagebox-img8',
            ),
          ),
        ),
        1 => 
         array(
           'id' => 'middle_banner_imagebox_1',
           'type' => 'box',
           'child' => 
          array (
            0 => 
             array(
               'type' => 'html',
               'tag' => 'img',
               'id' => 'middle_banner_imagebox_1-img23',
            ),
          ),
        ),
        2 => 
         array(
           'id' => 'middle_banner_imagebox_2',
           'type' => 'box',
           'child' => 
          array (
            0 => 
             array(
               'type' => 'html',
               'tag' => 'img',
               'id' => 'middle_banner_imagebox_2-img24',
            ),
          ),
        ),
        3 => 
         array(
           'id' => 'middle_banner_imagebox_3',
           'type' => 'box',
           'child' => 
          array (
            0 => 
             array(
               'type' => 'html',
               'tag' => 'img',
               'id' => 'middle_banner_imagebox_3-img25',
            ),
          ),
        ),
        4 => 
         array(
           'id' => 'middle_banner_imagebox_4',
           'type' => 'box',
           'child' => 
          array (
            0 => 
             array(
               'type' => 'html',
               'tag' => 'img',
               'id' => 'middle_banner_imagebox_4-img26',
            ),
          ),
        ),
      ),
    ),
  ),
  'style' => 
   array(
     'middle_banner_imagebox_4-img26' => 
     array(
       'width' => '100%',
       'height' => '550px',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'middle_banner_imagebox_4' => 
     array(
       'width' => '100%',
       'height' => 'auto',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '20px',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'middle_banner_imagebox_3-img25' => 
     array(
       'width' => '100%',
       'height' => '450px',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'middle_banner_imagebox_3' => 
     array(
       'width' => '94%',
       'height' => 'auto',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => 'auto',
       'marginLeft' => 'auto',
       'marginBottom' => '20px',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'middle_banner_imagebox_2-img24' => 
     array(
       'width' => '100%',
       'height' => '250px',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'middle_banner_imagebox_2' => 
     array(
       'width' => '100%',
       'height' => 'auto',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '20px',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'middle_banner_imagebox_1-img23' => 
     array(
       'width' => '100%',
       'height' => '450px',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'middle_banner_imagebox_1' => 
     array(
       'width' => '94%',
       'height' => 'auto',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => 'auto',
       'marginLeft' => 'auto',
       'marginBottom' => '20px',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'middle_banner_imagebox-img8' => 
     array(
       'width' => '100%',
       'height' => '550px',
       'backgroundColor' => '#FF000000',
       'color' => '#FF000000',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'middle_banner_imagebox' => 
     array(
       'width' => '100%',
       'height' => 'auto',
       'backgroundColor' => '#FF000000',
       'color' => '#FF000000',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '20px',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'middle_banner' => 
     array(
       'width' => '100%',
       'height' => 'auto',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'space-between',
    ),
     'bannerTop_right_bottom-img10' => 
     array(
       'width' => '100%',
       'height' => '100%',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '10px',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '10px',
       'borderBottomLeftRadius' => '10px',
       'borderBottomRightRadius' => '10px',
       'borderTopLeftRadius' => '10px',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'center',
       'justifyContent' => 'end',
    ),
     'bannerTop_right_bottom-img7' => 
     array(
       'width' => '100%',
       'height' => '100%',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '5px',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '10px',
       'borderBottomLeftRadius' => '10px',
       'borderBottomRightRadius' => '10px',
       'borderTopLeftRadius' => '10px',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'center',
       'justifyContent' => 'end',
    ),
     'bannerTop_left-img6' => 
     array(
       'width' => '100%',
       'height' => '100%',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'bannerTop_right_top-img5' => 
     array(
       'width' => '100%',
       'height' => '100%',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '10px',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '10px',
       'borderBottomLeftRadius' => '10px',
       'borderBottomRightRadius' => '10px',
       'borderTopLeftRadius' => '10px',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'center',
       'justifyContent' => 'end',
    ),
     'bannerTop_right_top-img4' => 
     array(
       'width' => '100%',
       'height' => '100%',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '5px',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '10px',
       'borderBottomLeftRadius' => '10px',
       'borderBottomRightRadius' => '10px',
       'borderTopLeftRadius' => '10px',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'center',
       'justifyContent' => 'end',
    ),
     'bannerTop_right_bottom' => 
     array(
       'width' => '100%',
       'height' => 'calc(50% - 10px)',
       'backgroundColor' => '#9CCC6500',
       'color' => '',
       'marginTop' => '5px',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'center',
       'justifyContent' => 'space-between',
    ),
     'bannerTop_right_top' => 
     array(
       'width' => '100%',
       'height' => 'calc(50% - 10px)',
       'backgroundColor' => '#26C6DA00',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '5px',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'center',
       'justifyContent' => 'space-between',
    ),
     'bannerTop_left' => 
     array(
       'width' => 'calc(50% - 20px)',
       'height' => 'auto',
       'backgroundColor' => '#FF000000',
       'color' => '',
       'marginTop' => '',
       'marginRight' => 'auto',
       'marginLeft' => 'auto',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'center',
       'justifyContent' => 'start',
    ),
     'bannerTop_right' => 
     array(
       'width' => 'calc(50% - 20px)',
       'height' => 'auto',
       'backgroundColor' => '#3F51B500',
       'color' => '',
       'marginTop' => '',
       'marginRight' => 'auto',
       'marginLeft' => 'auto',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'center',
       'justifyContent' => 'start',
    ),
     'slider_left_box-img3' => 
     array(
       'width' => '100%',
       'height' => '220px',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '8px',
       'borderBottomLeftRadius' => '8px',
       'borderBottomRightRadius' => '8px',
       'borderTopLeftRadius' => '8px',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
    ),
     'slider_left_box-img2' => 
     array(
       'width' => '100%',
       'height' => '210px',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '20px',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '8px',
       'borderBottomLeftRadius' => '8px',
       'borderBottomRightRadius' => '8px',
       'borderTopLeftRadius' => '8px',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
    ),
     'slider_right_box-slider1' => 
    array (
    ),
     'slider_right_box' => 
     array(
       'width' => '100%',
       'height' => '600px',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'slider' => 
     array(
       'width' => '100%',
       'height' => 'auto',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '0',
       'marginRight' => '0',
       'marginLeft' => '0',
       'marginBottom' => '20px',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'product_list-incredibleOffers1' => 
    array (
    ),
     'right_box-img1' => 
     array(
       'width' => '200px',
       'height' => '',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '25px',
       'marginRight' => '50px',
       'marginLeft' => '30px',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
    ),
     'incredibleOffers' => 
     array(
       'width' => '94%',
       'height' => 'auto',
       'backgroundColor' => '#F6F6F6',
       'color' => '#FFFFFFFF',
       'marginTop' => '',
       'marginRight' => 'auto',
       'marginLeft' => 'auto',
       'marginBottom' => '20px',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'center',
       'justifyContent' => 'space-between',
    ),
  ),
  'tags' => 
   array(
     'horizontal_product_list' => 
    array (
    ),
     'img' => 
     array(
       'middle_banner_imagebox_4-img26' => 
       array(
         'src' => 'https://oncogenedev.ir/files/gallery/image_14771562414851.jpg',
         'link' => 'link',
         'hoverSrc' => '',
      ),
       'middle_banner_imagebox_3-img25' => 
       array(
         'src' => 'https://oncogenedev.ir/files/gallery/image_6801569017126.jpg',
         'link' => 'link',
         'hoverSrc' => '',
      ),
       'middle_banner_imagebox_2-img24' => 
       array(
         'src' => 'https://oncogenedev.ir/files/gallery/image_14771562414851.jpg',
         'link' => 'link',
         'hoverSrc' => '',
      ),
       'middle_banner_imagebox_1-img23' => 
       array(
         'src' => 'https://oncogenedev.ir/files/gallery/image_12281562400140.jpg',
         'link' => 'link',
         'hoverSrc' => '',
      ),
       'middle_banner_imagebox-img8' => 
       array(
         'src' => 'https://oncogenedev.ir/files/gallery/image_14771562414851.jpg',
         'link' => 'link',
         'hoverSrc' => '',
      ),
       'bannerTop_right_bottom-img10' => 
       array(
         'src' => 'https://oncogenedev.ir/files/images/0c99fa717c04310ca07b6db54a52d0ffac8fdce3_1598113005.jpg',
         'link' => 'link',
         'hoverSrc' => '',
      ),
       'bannerTop_right_bottom-img7' => 
       array(
         'src' => 'https://oncogenedev.ir/files/images/0c99fa717c04310ca07b6db54a52d0ffac8fdce3_1598113005.jpg',
         'link' => 'link',
         'hoverSrc' => '',
      ),
       'bannerTop_left-img6' => 
       array(
         'src' => 'https://oncogenedev.ir/files/review/1409422.jpg',
         'link' => 'link',
         'hoverSrc' => '',
      ),
       'bannerTop_right_top-img5' => 
       array(
         'src' => 'https://oncogenedev.ir/files/images/0c99fa717c04310ca07b6db54a52d0ffac8fdce3_1598113005.jpg',
         'link' => 'link',
         'hoverSrc' => '',
      ),
       'bannerTop_right_top-img4' => 
       array(
         'src' => 'https://oncogenedev.ir/files/images/0c99fa717c04310ca07b6db54a52d0ffac8fdce3_1598113005.jpg',
         'link' => 'link2',
         'hoverSrc' => '',
      ),
       'slider_left_box-img3' => 
       array(
         'src' => 'http://localhost/oncogene/public/files/images/0c99fa717c04310ca07b6db54a52d0ffac8fdce3_1598113005.jpg',
         'link' => '',
      ),
       'slider_left_box-img2' => 
       array(
         'src' => 'http://localhost/oncogene/public/files/images/1773cee3eb3bc9ece26d37cc3d0eda2799218bef_1597479643.jpg',
         'link' => '',
      ),
       'right_box-img1' => 
       array(
         'src' => 'http://localhost/laravelCMS/public/files/images/b6c724a0.png',
         'link' => '',
      ),
    ),
     'incredibleOffers' => 
     array(
       'product_list-incredibleOffers1' => 
       array(
         'cat1' => '',
         'cat2' => '',
         'view' => 'incredibleOffers::front.product_list',
      ),
    ),
     'slider' => 
     array(
       'slider_right_box-slider1' => 
       array(
         'view' => 'sliders::desktop',
      ),
    ),
  ),
  'responsive_style' => 
   array(
     'max_slider_right_box_1000' => 
     array(
       'width' => '70%',
       'height' => '400px',
       'type' => 'min',
    ),
     'max_slider_left_box-img2_1000' => 
     array(
       'width' => '100%',
       'height' => '180px',
       'type' => 'min',
    ),
     'max_slider_left_box-img3_1000' => 
     array(
       'width' => '100%',
       'height' => '200px',
       'type' => 'min',
    ),
     'max_slider_left_box_1000' => 
     array(
       'width' => '30%',
       'height' => '400px',
       'type' => 'min',
    ),
  ),
)?>