<?php $desktop_layout_footer=array (
    'rows' =>
        array (
            0 =>
                array(
                    'id' => 'c_footer',
                    'child' =>
                        array (
                            0 =>
                                array(
                                    'id' => 'contacts2',
                                    'type' => 'box',
                                    'child' =>
                                        array (
                                            0 =>
                                                array(
                                                    'id' => 'contacts2_right_box',
                                                    'type' => 'box',
                                                    'child' =>
                                                        array (
                                                            0 =>
                                                                array(
                                                                    'type' => 'html',
                                                                    'tag' => 'card',
                                                                    'id' => 'contacts2_right_box-card5',
                                                                ),
                                                            1 =>
                                                                array(
                                                                    'type' => 'html',
                                                                    'tag' => 'card',
                                                                    'id' => 'contacts2_right_box-card6',
                                                                ),
                                                            2 =>
                                                                array(
                                                                    'type' => 'html',
                                                                    'tag' => 'card',
                                                                    'id' => 'contacts2_right_box-card7',
                                                                ),
                                                        ),
                                                ),
                                        ),
                                ),
                            1 =>
                                array(
                                    'id' => 'line3',
                                    'type' => 'box',
                                    'child' =>
                                        array (
                                            0 =>
                                                array(
                                                    'id' => 'line3_right_box',
                                                    'type' => 'box',
                                                    'child' =>
                                                        array (
                                                            0 =>
                                                                array(
                                                                    'type' => 'html',
                                                                    'tag' => 'img',
                                                                    'id' => 'line3_right_box-img6',
                                                                ),
                                                            1 =>
                                                                array(
                                                                    'type' => 'html',
                                                                    'tag' => 'img',
                                                                    'id' => 'line3_right_box-img7',
                                                                ),
                                                            2 =>
                                                                array(
                                                                    'type' => 'html',
                                                                    'tag' => 'img',
                                                                    'id' => 'line3_right_box-img4',
                                                                ),
                                                        ),
                                                ),
                                            1 =>
                                                array(
                                                    'id' => 'line3_left_box',
                                                    'type' => 'box',
                                                    'child' =>
                                                        array (
                                                            0 =>
                                                                array(
                                                                    'type' => 'html',
                                                                    'tag' => 'code',
                                                                    'id' => 'line3_left_box-code1',
                                                                ),
                                                        ),
                                                ),
                                        ),
                                ),
                            2 =>
                                array(
                                    'id' => 'line4',
                                    'type' => 'box',
                                    'child' =>
                                        array (
                                            0 =>
                                                array(
                                                    'type' => 'html',
                                                    'tag' => 'p',
                                                    'id' => 'line4-p2',
                                                ),
                                        ),
                                ),
                        ),
                ),
        ),
    'style' =>
        array(
            'line3_left_box-code1' =>
                array(
                    'width' => '',
                    'height' => '',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'line3_left_box' =>
                array(
                    'width' => '60%',
                    'height' => '200px',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'column',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'line3_right_box-img4' =>
                array(
                    'width' => '140px',
                    'height' => '',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '10px',
                    'marginRight' => '10px',
                    'marginLeft' => '10px',
                    'marginBottom' => '10px',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'line4-p2' =>
                array(
                    'width' => 'auto',
                    'height' => 'auto',
                    'backgroundColor' => '#FFFFFF00',
                    'color' => '',
                    'marginTop' => '1px',
                    'marginRight' => 'auto',
                    'marginLeft' => 'auto',
                    'marginBottom' => '',
                    'paddingTop' => '10px',
                    'paddingRight' => '10px',
                    'paddingLeft' => '10px',
                    'paddingBottom' => '10px',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'line5-p1' =>
                array (
                ),
            'line4' =>
                array(
                    'width' => '100%',
                    'height' => 'auto',
                    'backgroundColor' => '#1A237EFF',
                    'color' => '#FFFFFFFF',
                    'marginTop' => '1px',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'column',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'center',
                    'justifyContent' => 'start',
                ),
            'line3_right_box-img7' =>
                array(
                    'width' => '140px',
                    'height' => '',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '10px',
                    'marginRight' => '10px',
                    'marginLeft' => '10px',
                    'marginBottom' => '10px',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'line3_right_box-img6' =>
                array(
                    'width' => '140px',
                    'height' => '',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '10px',
                    'marginRight' => '10px',
                    'marginLeft' => '10px',
                    'marginBottom' => '10px',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'line3_right_box' =>
                array(
                    'width' => '40%',
                    'height' => 'auto',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '20px',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '20px',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'line3' =>
                array(
                    'width' => '94%',
                    'height' => 'auto',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => 'auto',
                    'marginLeft' => 'auto',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'contacts2_left_box-img5' =>
                array(
                    'width' => '40px',
                    'height' => '40px',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'contacts2_left_box-img4' =>
                array(
                    'width' => '40px',
                    'height' => '40px',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'contacts2_left_box-img3' =>
                array(
                    'width' => '40px',
                    'height' => '40px',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'contacts2_left_box-img2' =>
                array(
                    'width' => '40px',
                    'height' => '40px',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'contacts2_left_box-img1' =>
                array(
                    'width' => '40px',
                    'height' => '40px',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'contacts2_right_box-card7' =>
                array(
                    'width' => '',
                    'height' => '',
                    'backgroundColor' => '',
                    'color' => '#FFFFFFFF',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'contacts2_right_box-card6' =>
                array(
                    'width' => '',
                    'height' => '',
                    'backgroundColor' => '',
                    'color' => '#FFFFFFFF',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'contacts2_right_box-card5' =>
                array(
                    'width' => '',
                    'height' => '',
                    'backgroundColor' => '',
                    'color' => '#FFFFFFFF',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'contacts2_right_box' =>
                array(
                    'width' => '100%',
                    'height' => '60px',
                    'backgroundColor' => '',
                    'color' => '#FFFFFFFF',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '10px',
                    'paddingRight' => '15px',
                    'paddingLeft' => '10px',
                    'paddingBottom' => '10px',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'center',
                    'justifyContent' => 'space-between',
                ),
            'contacts2' =>
                array(
                    'width' => '94%',
                    'height' => 'auto',
                    'backgroundColor' => '#1A237EFF',
                    'color' => '',
                    'marginTop' => '20px',
                    'marginRight' => 'auto',
                    'marginLeft' => 'auto',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '10px',
                    'borderBottomLeftRadius' => '10px',
                    'borderBottomRightRadius' => '10px',
                    'borderTopLeftRadius' => '10px',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'end',
                ),
            'contacts_right_box-ul1' =>
                array(
                    'width' => '',
                    'height' => '',
                    'backgroundColor' => '',
                    'color' => '#757575FF',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'column',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'contacts_left_box-card4' =>
                array(
                    'width' => '165px',
                    'height' => '',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '10px',
                    'marginRight' => '10px',
                    'marginLeft' => '10px',
                    'marginBottom' => '10px',
                    'paddingTop' => '10px',
                    'paddingRight' => '10px',
                    'paddingLeft' => '10px',
                    'paddingBottom' => '10px',
                    'borderWidth' => '1px',
                    'borderColor' => '#E0E0E0FF',
                    'borderTopRightRadius' => '5px',
                    'borderBottomLeftRadius' => '5px',
                    'borderBottomRightRadius' => '5px',
                    'borderTopLeftRadius' => '5px',
                    'flexDirection' => 'column',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'center',
                    'justifyContent' => 'start',
                ),
            'contacts_left_box-card3' =>
                array(
                    'width' => '165px',
                    'height' => '',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '10px',
                    'marginRight' => '10px',
                    'marginLeft' => '10px',
                    'marginBottom' => '10px',
                    'paddingTop' => '10px',
                    'paddingRight' => '10px',
                    'paddingLeft' => '10px',
                    'paddingBottom' => '10px',
                    'borderWidth' => '1px',
                    'borderColor' => '#E0E0E0FF',
                    'borderTopRightRadius' => '5px',
                    'borderBottomLeftRadius' => '5px',
                    'borderBottomRightRadius' => '5px',
                    'borderTopLeftRadius' => '5px',
                    'flexDirection' => 'column',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'center',
                    'justifyContent' => 'start',
                ),
            'contacts_left_box-card2' =>
                array(
                    'width' => '165px',
                    'height' => '',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '10px',
                    'marginRight' => '10px',
                    'marginLeft' => '10px',
                    'marginBottom' => '10px',
                    'paddingTop' => '10px',
                    'paddingRight' => '10px',
                    'paddingLeft' => '10px',
                    'paddingBottom' => '10px',
                    'borderWidth' => '1px',
                    'borderColor' => '#E0E0E0FF',
                    'borderTopRightRadius' => '5px',
                    'borderBottomLeftRadius' => '5px',
                    'borderBottomRightRadius' => '5px',
                    'borderTopLeftRadius' => '5px',
                    'flexDirection' => 'column',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'center',
                ),
            'contacts_left_box-card1' =>
                array(
                    'width' => '165px',
                    'height' => '',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '10px',
                    'marginRight' => '10px',
                    'marginLeft' => '10px',
                    'marginBottom' => '10px',
                    'paddingTop' => '10px',
                    'paddingRight' => '10px',
                    'paddingLeft' => '10px',
                    'paddingBottom' => '10px',
                    'borderWidth' => '1px',
                    'borderColor' => '#E0E0E0FF',
                    'borderTopRightRadius' => '5px',
                    'borderBottomLeftRadius' => '5px',
                    'borderBottomRightRadius' => '5px',
                    'borderTopLeftRadius' => '5px',
                    'flexDirection' => 'column',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'center',
                    'justifyContent' => 'start',
                ),
            'c_footer' =>
                array(
                    'width' => '100%',
                    'height' => 'auto',
                    'backgroundColor' => '#FFFFFFFF',
                    'color' => '',
                    'marginTop' => '20px',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '20px',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '1px 0 0 0',
                    'borderColor' => '#E0E0E2FF',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'column',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
        ),
    'tags' =>
        array(
            'horizontal_product_list' =>
                array (
                ),
            'slider' =>
                array (
                ),
            'incredibleOffers' =>
                array (
                ),
            'img' =>
                array(
                    'line3_right_box-img4' =>
                        array(
                            'src' => 'https://oncogenedev.ir/files/images/1629708254.png',
                            'link' => '',
                            'hoverSrc' => '',
                        ),
                    'line3_right_box-img7' =>
                        array(
                            'src' => 'https://oncogenedev.ir/files/images/1629708254.png',
                            'link' => '',
                            'hoverSrc' => '',
                        ),
                    'line3_right_box-img6' =>
                        array(
                            'src' => 'https://oncogenedev.ir/files/images/1629708254.png',
                            'link' => '',
                            'hoverSrc' => '',
                        ),
                    'contacts2_left_box-img5' =>
                        array(
                            'src' => 'http://localhost/digishop/public/files/images/1628234408.svg',
                            'link' => '',
                            'hoverSrc' => 'http://localhost/digishop/public/files/images/1628237385.svg',
                        ),
                    'contacts2_left_box-img4' =>
                        array(
                            'src' => 'http://localhost/digishop/public/files/images/1628234431.svg',
                            'link' => '',
                            'hoverSrc' => 'http://localhost/digishop/public/files/images/1628238783.svg',
                        ),
                    'contacts2_left_box-img3' =>
                        array(
                            'src' => 'http://localhost/digishop/public/files/images/1628234420.svg',
                            'link' => 'http://localhost/digishop/public/files/images/1628234420.svg',
                            'hoverSrc' => 'http://localhost/digishop/public/files/images/1628238830.svg',
                        ),
                    'contacts2_left_box-img2' =>
                        array(
                            'src' => 'http://localhost/digishop/public/files/images/1628234416.svg',
                            'link' => '',
                            'hoverSrc' => 'http://localhost/digishop/public/files/images/1628238909.svg',
                        ),
                    'contacts2_left_box-img1' =>
                        array(
                            'src' => 'http://localhost/digishop/public/files/images/1628236560.svg',
                            'link' => '',
                            'hoverSrc' => 'http://localhost/digishop/public/files/images/1628238872.svg',
                        ),
                ),
            'card' =>
                array(
                    'contacts2_right_box-card7' =>
                        array(
                            'title' => 'ساعات پاسخگویی : ',
                            'content' => 'شنبه تا چهارشنبه ۸:۳۰ الی ۲۱ - پنجشنبه ۹ الی ۲۰',
                            'img' => '',
                            'titleColor' => '#FFFFFFFF',
                            'titlePadding' => '',
                            'titleSize' => '15px',
                            'contentPadding' => '0px 10px',
                            'contentSize' => '15px',
                            'link' => '',
                            'icon' => '',
                            'iconColor' => '#FFFFFFFF',
                            'imgWidth' => '',
                            'imageMargin' => '',
                        ),
                    'contacts2_right_box-card6' =>
                        array(
                            'title' => 'آدرس ایمیل:',
                            'content' => 'info@oncogene.ir',
                            'img' => '',
                            'titleColor' => '#FFFFFFFF',
                            'titlePadding' => '',
                            'titleSize' => '15px',
                            'contentPadding' => '0px 10px',
                            'contentSize' => '15px',
                            'link' => '',
                            'icon' => '',
                            'iconColor' => '#FFFFFFFF',
                            'imgWidth' => '',
                            'imageMargin' => '',
                        ),
                    'contacts2_right_box-card5' =>
                        array(
                            'title' => 'شماره تماس : ',
                            'content' => '09196548587',
                            'img' => '',
                            'titleColor' => '#FFFFFFFF',
                            'titlePadding' => '',
                            'titleSize' => '15px',
                            'contentPadding' => '0px 10px',
                            'contentSize' => '15px',
                            'link' => '',
                            'icon' => '',
                            'iconColor' => '#FFFFFFFF',
                            'imgWidth' => '',
                            'imageMargin' => '',
                        ),
                    'contacts_left_box-card4' =>
                        array(
                            'title' => 'پشتیبانی تلفنی',
                            'content' => ' پاسخگوی سوالات شما ',
                            'img' => 'http://localhost/digishop/public/files/images/1628112012.svg',
                            'titleColor' => '#607D8BFF',
                            'titlePadding' => '10px 5px',
                            'titleSize' => '14px',
                            'contentPadding' => '0px 0px 10px 0px',
                            'contentSize' => '13px',
                            'link' => '',
                            'icon' => '',
                            'iconColor' => '',
                            'imgWidth' => '60px',
                            'imageMargin' => 'auto',
                        ),
                    'contacts_left_box-card3' =>
                        array(
                            'title' => ' گارانتی طلایی',
                            'content' => ' مهلت ۷ روز بازگشت کالا ',
                            'img' => 'http://localhost/digishop/public/files/images/1628111781.svg',
                            'titleColor' => '#607D8BFF',
                            'titlePadding' => '10px 5px',
                            'titleSize' => '14px',
                            'contentPadding' => '0px 0px 10px 0px',
                            'contentSize' => '13px',
                            'link' => '',
                            'icon' => '',
                            'iconColor' => '',
                            'imgWidth' => '60px',
                            'imageMargin' => 'auto',
                        ),
                    'contacts_left_box-card2' =>
                        array(
                            'title' => 'تضمین اصالت کالا ',
                            'content' => 'تمامی کالا ها با گارانتی معتبر ',
                            'img' => 'http://localhost/digishop/public/files/images/1628108096.svg',
                            'titleColor' => '#607D8BFF',
                            'titlePadding' => '10px 5px',
                            'titleSize' => '14px',
                            'contentPadding' => '0px 0px 10px 0px',
                            'contentSize' => '13px',
                            'link' => '',
                            'icon' => '',
                            'iconColor' => '',
                            'imgWidth' => '60px',
                            'imageMargin' => 'auto',
                        ),
                    'contacts_left_box-card1' =>
                        array(
                            'title' => 'ارسال سریع کالا ',
                            'content' => ' یک روز پس از سفارش ',
                            'img' => 'http://localhost/digishop/public/files/images/1628087162.svg',
                            'titleColor' => '#4527A0FF',
                            'titlePadding' => '10px 5px',
                            'titleSize' => '14px',
                            'contentPadding' => '0px 0px 10px 0px',
                            'contentSize' => '13px',
                            'link' => 'http://localhost/digishop/public/faq',
                            'icon' => '',
                            'iconColor' => '',
                            'imgWidth' => '60px',
                            'imageMargin' => 'auto',
                        ),
                ),
            'ul' =>
                array(
                    'contacts_right_box-ul1' =>
                        array(
                            'title' => 'آنکوژن',
                            'titleColor' => '#474747FF',
                            'titleSize' => '20px',
                            'titleIcon' => '',
                            'items' =>
                                array (
                                    0 =>
                                        array(
                                            'title' => 'درباره آنکوژن',
                                            'link' => '',
                                        ),
                                    1 =>
                                        array(
                                            'title' => 'تماس با ما',
                                            'link' => '',
                                        ),
                                ),
                            'itemPadding' => '5px 10px',
                            'hoverColor' => '#F1131FFF',
                        ),
                ),
            'code' =>
                array(
                    'line3_left_box-code1' =>
                        array(
                            'content' => '<p style=\'margin-top: 15px\'> about footer </p>',
                        ),
                ),
            'p' =>
                array(
                    'line4-p2' =>
                        array(
                            'content' => ' کلیه حقوق مادی و معنوی این سایت متعلق به آنکوژن بوده و انتشـار هرگونــه از مطالـب آن صرفا با ذکر نـام منبـع مجاز می بـاشد',
                            'showMore' => '',
                        ),
                    'line5-p1' =>
                        array(
                            'content' => '',
                        ),
                ),
        ),
    'responsive_style' =>
        array(
        ),
)?>
