<?php $mobile_home_content=array (
    'rows' =>
        array (
            0 =>
                array(
                    'id' => 'slider',
                    'child' =>
                        array (
                            0 =>
                                array(
                                    'type' => 'widget',
                                    'tag' => 'slider',
                                    'id' => 'slider-slider1',
                                ),
                        ),
                ),
            1 =>
                array(
                    'id' => 'ads1',
                    'child' =>
                        array (
                            0 =>
                                array(
                                    'type' => 'html',
                                    'tag' => 'img',
                                    'id' => 'ads1-img4',
                                ),
                        ),
                ),
            2 =>
                array(
                    'id' => 'four_box_ads',
                    'child' =>
                        array (
                            0 =>
                                array(
                                    'id' => 'four_box_ads_top_row',
                                    'type' => 'box',
                                    'child' =>
                                        array (
                                            0 =>
                                                array(
                                                    'id' => 'ads_top_right',
                                                    'type' => 'box',
                                                    'child' =>
                                                        array (
                                                            0 =>
                                                                array(
                                                                    'type' => 'html',
                                                                    'tag' => 'img',
                                                                    'id' => 'ads_top_right-img8',
                                                                ),
                                                        ),
                                                ),
                                            1 =>
                                                array(
                                                    'id' => 'ads_top_left',
                                                    'type' => 'box',
                                                    'child' =>
                                                        array (
                                                            0 =>
                                                                array(
                                                                    'type' => 'html',
                                                                    'tag' => 'img',
                                                                    'id' => 'ads_top_left-img9',
                                                                ),
                                                        ),
                                                ),
                                        ),
                                ),
                            1 =>
                                array(
                                    'id' => 'four_box_ads_bottom_row',
                                    'type' => 'box',
                                    'child' =>
                                        array (
                                            0 =>
                                                array(
                                                    'id' => 'ads_bottom_right',
                                                    'type' => 'box',
                                                    'child' =>
                                                        array (
                                                            0 =>
                                                                array(
                                                                    'type' => 'html',
                                                                    'tag' => 'img',
                                                                    'id' => 'ads_bottom_right-img4',
                                                                ),
                                                        ),
                                                ),
                                            1 =>
                                                array(
                                                    'id' => 'ads_bottom_left',
                                                    'type' => 'box',
                                                    'child' =>
                                                        array (
                                                            0 =>
                                                                array(
                                                                    'type' => 'html',
                                                                    'tag' => 'img',
                                                                    'id' => 'ads_bottom_left-img5',
                                                                ),
                                                        ),
                                                ),
                                        ),
                                ),
                        ),
                ),
            3 =>
                array(
                    'id' => 'middle_banner',
                    'child' =>
                        array (
                            0 =>
                                array(
                                    'id' => 'middle_banner_imagebox',
                                    'type' => 'box',
                                    'child' =>
                                        array (
                                            0 =>
                                                array(
                                                    'type' => 'html',
                                                    'tag' => 'img',
                                                    'id' => 'middle_banner_imagebox-img6',
                                                ),
                                        ),
                                ),
                            1 =>
                                array(
                                    'id' => 'middle_banner_imagebox_1',
                                    'type' => 'box',
                                    'child' =>
                                        array (
                                            0 =>
                                                array(
                                                    'type' => 'html',
                                                    'tag' => 'img',
                                                    'id' => 'middle_banner_imagebox_1-img7',
                                                ),
                                        ),
                                ),
                            2 =>
                                array(
                                    'id' => 'middle_banner_imagebox_2',
                                    'type' => 'box',
                                    'child' =>
                                        array (
                                            0 =>
                                                array(
                                                    'type' => 'html',
                                                    'tag' => 'img',
                                                    'id' => 'middle_banner_imagebox_2-img8',
                                                ),
                                        ),
                                ),
                            3 =>
                                array(
                                    'id' => 'middle_banner_imagebox_3',
                                    'type' => 'box',
                                    'child' =>
                                        array (
                                            0 =>
                                                array(
                                                    'type' => 'html',
                                                    'tag' => 'img',
                                                    'id' => 'middle_banner_imagebox_3-img9',
                                                ),
                                        ),
                                ),
                            4 =>
                                array(
                                    'id' => 'middle_banner_imagebox_4',
                                    'type' => 'box',
                                    'child' =>
                                        array (
                                            0 =>
                                                array(
                                                    'type' => 'html',
                                                    'tag' => 'img',
                                                    'id' => 'middle_banner_imagebox_4-img10',
                                                ),
                                        ),
                                ),
                        ),
                ),
        ),
    'style' =>
        array(
            'middle_banner_imagebox_4-img10' =>
                array(
                    'width' => '100%',
                    'height' => '150px',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'middle_banner_imagebox_4' =>
                array(
                    'width' => '100%',
                    'height' => 'auto',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'column',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'middle_banner_imagebox_3-img9' =>
                array(
                    'width' => '100%',
                    'height' => '125px',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'middle_banner_imagebox_3' =>
                array(
                    'width' => '100%',
                    'height' => 'auto',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '10px',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '10px',
                    'paddingLeft' => '10px',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'column',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'middle_banner_imagebox_2-img8' =>
                array(
                    'width' => '100%',
                    'height' => '100px',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'middle_banner_imagebox_2' =>
                array(
                    'width' => '100%',
                    'height' => 'auto',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '10px',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'column',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'middle_banner_imagebox_1-img7' =>
                array(
                    'width' => '100%',
                    'height' => '125px',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'middle_banner_imagebox_1' =>
                array(
                    'width' => '100%',
                    'height' => 'auto',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '10px',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '10px',
                    'paddingLeft' => '10px',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'column',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'middle_banner_imagebox-img6' =>
                array(
                    'width' => '100%',
                    'height' => '150px',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'middle_banner_imagebox' =>
                array(
                    'width' => '100%',
                    'height' => 'auto',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '10px',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'column',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'middle_banner' =>
                array(
                    'width' => '100%',
                    'height' => 'auto',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'column',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'ads_bottom_left-img5' =>
                array(
                    'width' => '100%',
                    'height' => 'auto',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'ads_bottom_right-img4' =>
                array(
                    'width' => '100%',
                    'height' => 'auto',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'ads_bottom_left' =>
                array(
                    'width' => '50%',
                    'height' => 'auto',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '5px',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'column',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'ads_bottom_right' =>
                array(
                    'width' => '50%',
                    'height' => 'auto',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '5px',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'column',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'ads_top_left-img9' =>
                array(
                    'width' => '100%',
                    'height' => 'auto',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'ads_top_right-img8' =>
                array(
                    'width' => '100%',
                    'height' => 'auto',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'ads_top_left' =>
                array(
                    'width' => '50%',
                    'height' => 'auto',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '5px',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'column',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'ads_top_right' =>
                array(
                    'width' => '50%',
                    'height' => 'auto',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '5px',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'column',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'four_box_ads_bottom_row' =>
                array(
                    'width' => '100%',
                    'height' => 'auto',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '10px',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '10px',
                    'paddingLeft' => '10px',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'four_box_ads_top_row' =>
                array(
                    'width' => '100%',
                    'height' => 'auto',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '10px',
                    'paddingLeft' => '10px',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'four_box_ads' =>
                array(
                    'width' => '100%',
                    'height' => 'auto',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'column',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'left-incredibleOffers1' =>
                array (
                ),
            'right-img3' =>
                array(
                    'width' => '100%',
                    'height' => '',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '10px',
                    'paddingRight' => '10px',
                    'paddingLeft' => '10px',
                    'paddingBottom' => '10px',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                ),
            'ads1-img4' =>
                array(
                    'width' => '100%',
                    'height' => '',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '10px',
                    'borderBottomLeftRadius' => '10px',
                    'borderBottomRightRadius' => '10px',
                    'borderTopLeftRadius' => '10px',
                    'flexDirection' => 'row',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'ads1' =>
                array(
                    'width' => '100%',
                    'height' => 'auto',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '10px',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '10px',
                    'paddingTop' => '',
                    'paddingRight' => '10px',
                    'paddingLeft' => '10px',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '10px',
                    'borderBottomLeftRadius' => '10px',
                    'borderBottomRightRadius' => '10px',
                    'borderTopLeftRadius' => '10px',
                    'flexDirection' => 'column',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
            'slider-slider1' =>
                array (
                ),
            'slider' =>
                array(
                    'width' => '100%',
                    'height' => '200px',
                    'backgroundColor' => '',
                    'color' => '',
                    'marginTop' => '',
                    'marginRight' => '',
                    'marginLeft' => '',
                    'marginBottom' => '',
                    'paddingTop' => '1px',
                    'paddingRight' => '',
                    'paddingLeft' => '',
                    'paddingBottom' => '',
                    'borderWidth' => '0px',
                    'borderColor' => '',
                    'borderTopRightRadius' => '',
                    'borderBottomLeftRadius' => '',
                    'borderBottomRightRadius' => '',
                    'borderTopLeftRadius' => '',
                    'flexDirection' => 'column',
                    'borderStyle' => 'solid',
                    'display' => 'flex',
                    'textAlign' => 'right',
                    'justifyContent' => 'start',
                ),
        ),
    'tags' =>
        array(
            'horizontal_product_list' =>
                array (
                ),
            'slider' =>
                array(
                    'slider-slider1' =>
                        array(
                            'view' => 'sliders::desktop',
                        ),
                ),
            'img' =>
                array(
                    'middle_banner_imagebox_4-img10' =>
                        array(
                            'src' => 'https://oncogenedev.ir/files/gallery/image_14771562414851.jpg',
                            'link' => 'link',
                            'hoverSrc' => '',
                        ),
                    'middle_banner_imagebox_3-img9' =>
                        array(
                            'src' => 'https://oncogenedev.ir/files/gallery/image_12281562400140.jpg',
                            'link' => 'link',
                            'hoverSrc' => '',
                        ),
                    'middle_banner_imagebox_2-img8' =>
                        array(
                            'src' => 'https://oncogenedev.ir/files/gallery/image_14771562414851.jpg',
                            'link' => '',
                            'hoverSrc' => '',
                        ),
                    'middle_banner_imagebox_1-img7' =>
                        array(
                            'src' => 'https://oncogenedev.ir/files/gallery/image_12281562400140.jpg',
                            'link' => 'link',
                            'hoverSrc' => '',
                        ),
                    'middle_banner_imagebox-img6' =>
                        array(
                            'src' => 'https://oncogenedev.ir/files/gallery/image_14771562414851.jpg',
                            'link' => '',
                            'hoverSrc' => '',
                        ),
                    'ads_bottom_left-img5' =>
                        array(
                            'src' => 'https://oncogenedev.ir/files/slider/desktop1606253050.jpg',
                            'link' => 'link',
                            'hoverSrc' => '',
                        ),
                    'ads_bottom_right-img4' =>
                        array(
                            'src' => 'https://oncogenedev.ir/files/slider/desktop1606253050.jpg',
                            'link' => 'link',
                            'hoverSrc' => '',
                        ),
                    'ads_top_left-img9' =>
                        array(
                            'src' => 'https://oncogenedev.ir/files/slider/desktop1606253050.jpg',
                            'link' => 'link',
                            'hoverSrc' => '',
                        ),
                    'ads_top_right-img8' =>
                        array(
                            'src' => 'https://oncogenedev.ir/files/slider/desktop1606253050.jpg',
                            'link' => 'link',
                            'hoverSrc' => '',
                        ),
                    'right-img3' =>
                        array(
                            'src' => 'http://localhost/seirkala/public/files/upload/63494995.png',
                            'link' => '',
                        ),
                    'right-img2' =>
                        array(
                            'src' => '',
                            'link' => '',
                        ),
                    'ads1-img4' =>
                        array(
                            'src' => 'https://oncogenedev.ir/files/slider/desktop1606253050.jpg',
                            'link' => 'link',
                        ),
                ),
            'incredibleOffers' =>
                array(
                    'left-incredibleOffers1' =>
                        array(
                            'cat1' => '',
                            'cat2' => '',
                            'view' => 'incredibleOffers::front.product_list',
                        ),
                ),
        ),
    'responsive_style' =>
        array(
        ),
)?>
