<?php $mobile_layout_footer=array (
  'rows' =>
  array (
    0 =>
     array(
       'id' => 'footer',
       'child' =>
      array (
        0 =>
         array(
           'id' => 'contacts_footer_mobile',
           'type' => 'box',
           'child' =>
          array (
            0 =>
             array(
               'id' => 'contacts_footer_mobile_top',
               'type' => 'box',
               'child' =>
              array (
                0 =>
                 array(
                   'type' => 'html',
                   'tag' => 'card',
                   'id' => 'contacts_footer_mobile_top-card2',
                ),
              ),
            ),
            1 =>
             array(
               'id' => 'contacts_footer_mobile_middle',
               'type' => 'box',
               'child' =>
              array (
                0 =>
                 array(
                   'type' => 'html',
                   'tag' => 'card',
                   'id' => 'contacts_footer_mobile_middle-card3',
                ),
              ),
            ),
            2 =>
             array(
               'id' => 'contacts_footer_mobile_bottom',
               'type' => 'box',
               'child' =>
              array (
                0 =>
                 array(
                   'type' => 'html',
                   'tag' => 'card',
                   'id' => 'contacts_footer_mobile_bottom-card4',
                ),
              ),
            ),
          ),
        ),
        1 =>
         array(
           'id' => 'about_footer_mobile',
           'type' => 'box',
           'child' =>
          array (
            0 =>
             array(
               'type' => 'html',
               'tag' => 'code',
               'id' => 'about_footer_mobile-code1',
            ),
          ),
        ),
        2 =>
         array(
           'id' => 'logo_footer_mobile',
           'type' => 'box',
           'child' =>
          array (
            0 =>
             array(
               'type' => 'html',
               'tag' => 'img',
               'id' => 'logo_footer_mobile-img1',
            ),
          ),
        ),
        3 =>
         array(
           'id' => 'icon_footer_mobile',
           'type' => 'box',
           'child' =>
          array (
            0 =>
             array(
               'type' => 'html',
               'tag' => 'img',
               'id' => 'icon_footer_mobile-img2',
            ),
            1 =>
             array(
               'type' => 'html',
               'tag' => 'img',
               'id' => 'icon_footer_mobile-img3',
            ),
          ),
        ),
      ),
    ),
    1 =>
     array(
       'id' => 'copy_right',
       'child' =>
      array (
        0 =>
         array(
           'type' => 'html',
           'tag' => 'p',
           'id' => 'copy_right-p1',
        ),
      ),
    ),
  ),
  'style' =>
   array(
     'icon_footer_mobile-img3' =>
     array(
       'width' => '140px',
       'height' => '',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'icon_footer_mobile-img2' =>
     array(
       'width' => '140px',
       'height' => '',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'icon_footer_mobile' =>
     array(
       'width' => '100%',
       'height' => 'auto',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'space-between',
    ),
     'logo_footer_mobile-img1' =>
     array(
       'width' => '140px',
       'height' => '',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '0',
       'marginRight' => 'auto',
       'marginLeft' => 'auto',
       'marginBottom' => '0',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'center',
       'justifyContent' => 'start',
    ),
     'logo_footer_mobile' =>
     array(
       'width' => '100%',
       'height' => 'auto',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '1px 0 0 0',
       'borderColor' => '#E0E0E1FF',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'center',
       'justifyContent' => 'start',
    ),
     'contacts_footer_mobile_bottom-card4' =>
     array(
       'width' => '',
       'height' => '',
       'backgroundColor' => '',
       'color' => '#FFFFFFFF',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'space-between',
    ),
     'contacts_footer_mobile_middle-card3' =>
     array(
       'width' => '',
       'height' => '',
       'backgroundColor' => '#FFFFFF00',
       'color' => '#FFFFFFFF',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '#FFFFFFFF',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'space-between',
    ),
     'contacts_footer_mobile_top-card2' =>
     array(
       'width' => '100%',
       'height' => '100%',
       'backgroundColor' => '#FFFFFF00',
       'color' => '#FFFFFFFF',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '#FFFFFFFF',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'center',
       'justifyContent' => 'space-between',
    ),
     'about_footer_mobile-code1' =>
     array(
       'width' => '',
       'height' => '',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'about_footer_mobile' =>
     array(
       'width' => '100%',
       'height' => 'auto',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'center',
       'justifyContent' => 'space-between',
    ),
     'contacts_footer_mobile_bottom' =>
     array(
       'width' => '100%',
       'height' => 'auto',
       'backgroundColor' => '#1A237EFF',
       'color' => '#FFFFFFFF',
       'marginTop' => '1px',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '10px',
       'paddingLeft' => '10px',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '3px',
       'borderBottomLeftRadius' => '3px',
       'borderBottomRightRadius' => '3px',
       'borderTopLeftRadius' => '3px',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'space-between',
    ),
     'contacts_footer_mobile_middle' =>
     array(
       'width' => '100%',
       'height' => 'auto',
       'backgroundColor' => '#1A237EFF',
       'color' => '#FFFFFFFF',
       'marginTop' => '1px',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '10px',
       'paddingLeft' => '10px',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '#FFFFFFFF',
       'borderTopRightRadius' => '3px',
       'borderBottomLeftRadius' => '3px',
       'borderBottomRightRadius' => '3px',
       'borderTopLeftRadius' => '3px',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'contacts_footer_mobile_top' =>
     array(
       'width' => '100%',
       'height' => 'auto',
       'backgroundColor' => '#1A237EFF',
       'color' => '#FFFFFFFF',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '10px',
       'paddingLeft' => '10px',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '#FFFFFFFF',
       'borderTopRightRadius' => '3px',
       'borderBottomLeftRadius' => '3px',
       'borderBottomRightRadius' => '3px',
       'borderTopLeftRadius' => '3px',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'contacts_footer_mobile' =>
     array(
       'width' => '100%',
       'height' => 'auto',
       'backgroundColor' => '',
       'color' => '',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'copy_right-p1' =>
     array(
       'width' => '100%',
       'height' => '',
       'backgroundColor' => '#1A237EFF',
       'color' => '#FFFFFFFF',
       'marginTop' => '',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '10px',
       'paddingRight' => '10px',
       'paddingLeft' => '10px',
       'paddingBottom' => '10px',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'row',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'center',
       'justifyContent' => 'space-between',
    ),
     'copy_right' =>
     array(
       'width' => '100%',
       'height' => 'auto',
       'backgroundColor' => '#FF000000',
       'color' => '#FF000000',
       'marginTop' => '1px',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '0px',
       'borderColor' => '',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
     'footer' =>
     array(
       'width' => '100%',
       'height' => 'auto',
       'backgroundColor' => '#FFFFFFFF',
       'color' => '',
       'marginTop' => '1px',
       'marginRight' => '',
       'marginLeft' => '',
       'marginBottom' => '',
       'paddingTop' => '',
       'paddingRight' => '',
       'paddingLeft' => '',
       'paddingBottom' => '',
       'borderWidth' => '1px 0 0 0',
       'borderColor' => '#E0E0E2FF',
       'borderTopRightRadius' => '',
       'borderBottomLeftRadius' => '',
       'borderBottomRightRadius' => '',
       'borderTopLeftRadius' => '',
       'flexDirection' => 'column',
       'borderStyle' => 'solid',
       'display' => 'flex',
       'textAlign' => 'right',
       'justifyContent' => 'start',
    ),
  ),
  'tags' =>
   array(
     'horizontal_product_list' =>
    array (
    ),
     'slider' =>
    array (
    ),
     'img' =>
     array(
       'icon_footer_mobile-img3' =>
       array(
         'src' => 'https://oncogenedev.ir/files/images/1629708254.png',
         'link' => '',
         'hoverSrc' => '',
      ),
       'icon_footer_mobile-img2' =>
       array(
         'src' => 'https://oncogenedev.ir/files/images/1629708254.png',
         'link' => '',
         'hoverSrc' => '',
      ),
       'logo_footer_mobile-img1' =>
       array(
         'src' => 'https://oncogenedev.ir/files/images/1629708254.png',
         'link' => '',
         'hoverSrc' => '',
      ),
    ),
     'card' =>
     array(
       'contacts_footer_mobile_bottom-card4' =>
       array(
         'title' => 'ساعات پاسخگویی : ',
         'content' => 'شنبه تا چهارشنبه ۸:۳۰ الی ۲۱ - پنجشنبه ۹ الی ۲۰',
         'img' => '',
         'titleColor' => '#FFFFFFFF',
         'titlePadding' => '5px',
         'titleSize' => '15px',
         'contentPadding' => '5px',
         'contentSize' => '15px',
         'link' => '',
         'icon' => '',
         'iconColor' => '#FFFFFFFF',
         'imgWidth' => '',
         'imageMargin' => '',
      ),
       'contacts_footer_mobile_middle-card3' =>
       array(
         'title' => 'آدرس ایمیل : ',
         'content' => 'info@oncogene.ir',
         'img' => '',
         'titleColor' => '#FFFFFFFF',
         'titlePadding' => '5px',
         'titleSize' => '15px',
         'contentPadding' => '5px',
         'contentSize' => '15px',
         'link' => '',
         'icon' => '',
         'iconColor' => '#FFFFFFFF',
         'imgWidth' => '',
         'imageMargin' => '',
      ),
       'contacts_footer_mobile_top-card2' =>
       array(
         'title' => 'شماره تماس : ',
         'content' => '09196548587',
         'img' => '',
         'titleColor' => '#FFFFFFFF',
         'titlePadding' => '5px',
         'titleSize' => '15px',
         'contentPadding' => '5px',
         'contentSize' => '15px',
         'link' => '',
         'icon' => '',
         'iconColor' => '#FF0000FF',
         'imgWidth' => '',
         'imageMargin' => '',
      ),
    ),
     'ul' =>
    array (
    ),
     'code' =>
     array(
       'about_footer_mobile-code1' =>
       array(
         'content' => '<p style=\'margin-top: 5px;text-align: center;width: 100%;\'> about footer </p>',
      ),
    ),
     'p' =>
     array(
       'copy_right-p1' =>
       array(
         'content' => 'کلیه حقوق مادی و معنوی این سایت متعلق به آنکوژن بوده
و انتشـار هرگونــه از مطالـب آن صرفا با ذکر نـام منبـع مجاز می بـاشد',
         'showMore' => false,
      ),
    ),
     'slide' =>
    array (
    ),
  ),
  'responsive_style' =>
   array(
  ),
)?>
